#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: Fight for the Future, defending our basic rights and freedoms
url: https://www.fightforthefuture.org
description: "Fight for the Future is dedicated to protecting and expanding the Internet's transformative power in our lives by creating civic campaigns that are engaging for millions of people."
timezone: America/New_York # Should be formatted like formal tz database
googleanalytics: UA-26576645-1

favicon: '/homepage/images/heart.png' # replace this with path to favicon if that’s a thing you’re doing.

author:
    googleid: 102356128596404327231
    twitterid: 382376904
    twitter: fightfortheftr

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:categories/:title/

collections:
  legacy_pages:
    output: true
    permalink: /:path/
  petitions:
    output: true
    permalink: /:categories/:path/
  redirects:
    output: true
    permalink: /:title/
  static_pages:
    output: true
    permalink: /:path/

prose:
  rooturl: 'site'
  ignore:
    - '_includes'
    - '_js'
    - '_layouts'
    - '_less'
    - '_plugins'
    - 'banners'
    - 'brand'
    - 'branding'
    - 'css'
    - 'echoimages'
    - 'js'
    - 'pipa'
    - 'press'
    - 'webfonts'
    - 'sitemap.xml'

  siteurl: 'https://www.fightforthefuture.org'
  media: 'site/img'
  metadata:
    '':
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ''

#############
# Compiling #
#############

exclude: ['img', 'images', 'css', 'js']
keep_files: ['img', 'images', 'css', 'js']


# this is commented bc each page has its own assets O_O
#exclude: [
#  'img', 'css', 'fonts', '**.haml',
#  '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico',
#]
#

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
